# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiln < Formula
  desc "Schema-first API compiler for Go"
  homepage "https://github.com/fisayoafolayan/kiln"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fisayoafolayan/kiln/releases/download/v0.1.12/kiln_0.1.12_darwin_amd64.tar.gz"
      sha256 "102387b7f810b80cf1490ad5d1d6af8338d6f2b67c3045a737af97745f31b72b"

      define_method(:install) do
        bin.install "kiln"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fisayoafolayan/kiln/releases/download/v0.1.12/kiln_0.1.12_darwin_arm64.tar.gz"
      sha256 "5077c5c3f6c4c5e8b3ed60debe11aff89f69076bd4c02e5c2bbec6a8e33f7d01"

      define_method(:install) do
        bin.install "kiln"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fisayoafolayan/kiln/releases/download/v0.1.12/kiln_0.1.12_linux_amd64.tar.gz"
      sha256 "f0727e99b7bfb6c06de39a67e356a55df1e2c7d2790c3562398211e2498b34cf"
      define_method(:install) do
        bin.install "kiln"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fisayoafolayan/kiln/releases/download/v0.1.12/kiln_0.1.12_linux_arm64.tar.gz"
      sha256 "102e472e07d7e1d4217798314bc8386b1d01c983372e38dbb20af4952623adc2"
      define_method(:install) do
        bin.install "kiln"
      end
    end
  end
end
