# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiln" do
  version "0.1.11"

  on_macos do
    on_intel do
      url "https://github.com/fisayoafolayan/kiln/releases/download/v#{version}/kiln_#{version}_darwin_amd64.tar.gz"
      sha256 "7d9ece10952619f97d543a74bbb6fb4b4460fad4ef548143aef7b4f19817a332"
    end
    on_arm do
      url "https://github.com/fisayoafolayan/kiln/releases/download/v#{version}/kiln_#{version}_darwin_arm64.tar.gz"
      sha256 "1dd14707aa9910703311ecd3627b8de50a2e3719f80decedd5cfbb5732628d6d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fisayoafolayan/kiln/releases/download/v#{version}/kiln_#{version}_linux_amd64.tar.gz"
      sha256 "87d215fe3397e528930d9ea29f6c02bec7ef89edfb6ef41970834b0be689b366"
    end
    on_arm do
      url "https://github.com/fisayoafolayan/kiln/releases/download/v#{version}/kiln_#{version}_linux_arm64.tar.gz"
      sha256 "09d6a1ad8ea4f7780aebb46980bfa5a62519e857b76ec0e3dd745ae79c9ac128"
    end
  end

  name "kiln"
  desc "Schema-first API compiler for Go"
  homepage "https://github.com/fisayoafolayan/kiln"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiln"

  # No zap stanza required

end
